name=Enc_TWAI
version=1.0.0
author=IchinosukeKaku
maintainer=IchinosukeKaku
sentence=A library for controlling Single-layer encoder motor using ESP32.
paragraph=This library allows for easy control of Single-layer encoder motor using an ESP32.
category=Device Control
url= nothing
architectures=esp32
includes=Enc_TWAI.h